### ISSUE TITLE
Date and Time is not loading right...

### ISSUE THREAD

**Issue by BenePhetes** [heksagonnet/piko#10]
![2024-05-24 02_59_17-Piko - Date and Time is not loading right](https://github.com/heksagonnet/piko/assets/32630610/7682d922-4836-45f3-b171-e7e2ce4bd686)

What do you think that caused that?
I'm running hugo on Windows 11.

**Comment by BenePhetes** [comment]
This is the fixed for that.

`{{- $scratch := newScratch }}

{{- if not .Date.IsZero -}}
{{- $date := .Date.Format "2006-01-02T15:04:05-0700" -}}
{{- $formattedDate := .Date.Format "January 2, 2006" -}}
{{- $scratch.Add "meta" (slice (printf "<time datetime='%s'>%s</time>" $date $formattedDate | safeHTML)) }}
{{- end }}

{{- if (.Param "ShowReadingTime") -}}
{{- $readingTime := printf "%d min" .ReadingTime -}}
{{- $scratch.Add "meta" (slice ($readingTime | safeHTML)) }}
{{- end }}

{{- with (partial "author.html" .) -}}
{{- $author := . -}}
{{- $scratch.Add "meta" (slice ($author | safeHTML)) }}
{{- end }}

{{- with ($scratch.Get "meta") -}}
{{- $meta := delimit . " · " -}}
{{- $meta | safeHTML -}}
{{- end -}}`

**Comment by yarik-kuznetsov** [comment]
Hey there @BenePhetes 
I have the same issue as you.
But I don't quite understand your workaround.
Could you explain in more detail how to apply your fix for the issue?
Thanks.

**Comment by BenePhetes** [comment]
Hi @yarik-kuznetsov, 
Sorry for the late reply.
I copied the post_meta.html from the Piko theme to the partials folder of the Hugo project and updated from there.
